services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./onboarding.db
      - DEBUG=true
      - ENVIRONMENT=development
